### ISSUE TITLE
why you did everything as "final"? 

### ISSUE THREAD

**Issue by aswierc** [structurizr-php/structurizr-php#57]
why you did everything as "final"? 
Guys, what if I want to show a few systems, or better, a lot of systems - would be good to extend by for example `SoftwareSystem` with their own properties. And then inject that kind of system to the builder which does a diagram. 

Ofc now I defined factories and build systems through the factory.

**Comment by norberttech** [comment]
Hey, 
making all classes final by design meant to reduce possible extension points that we could accidentally break by releasing a new version of the library. Could you please provide some code samples to help us understand your use case better?

**Comment by aswierc** [comment]
hello, sure, 
For example symfony yaml service configuration. I want to use DI to inject something 

```  
Architecture\Diagram\ContainerBoardDiagram:
        public: true
        class: 'Architecture\Diagram\ContainerBoardDiagram'
        arguments:
            $workspace: '@StructurizrPHP\Core\Workspace'
            $boardSystem: '@architecture.system.board'
```

```
    architecture.system.board:
        class: 'StructurizrPHP\Core\Model\SoftwareSystem'
        factory: ['@Architecture\Factory\SoftwareSystemFactory', 'create']
        arguments: ['Board', 'AppJobs.com']
```

as you can see everywhere I need to use factories, because I can't do 'extends' due the 'final' word. 

Also, we had to use reflection-api to set up properties on Workspace object, because there are no set-name and set-id methods and the class is 'final' as well.
